name: zego_zimkit_demo
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  zego_zimkit: ^1.7.0
  zego_uikit_prebuilt_call: ^3.7.0
  zego_uikit_signaling_plugin: ^2.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any
  dart_code_metrics: any
  import_sorter: any

import_sorter:
  comments: false

flutter:
  uses-material-design: true
